package thriftParser.Absyn; // Java Package generated by the BNF Converter.

public abstract class Default implements java.io.Serializable {
  public abstract <R,A> R accept(Default.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(thriftParser.Absyn.DefEmp p, A arg);
    public R visit(thriftParser.Absyn.DefInt p, A arg);
    public R visit(thriftParser.Absyn.DefEmptyStr p, A arg);
    public R visit(thriftParser.Absyn.DefStr p, A arg);

  }

}
