package thriftParser.Absyn; // Java Package generated by the BNF Converter.

public class DefEmptyStr extends Default {

  public DefEmptyStr() { }

  public <R,A> R accept(thriftParser.Absyn.Default.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof thriftParser.Absyn.DefEmptyStr) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
