package thriftParser.Absyn; // Java Package generated by the BNF Converter.

public class DefInt extends Default {
  public final Integer integer_;

  public DefInt(Integer p1) { integer_ = p1; }

  public <R,A> R accept(thriftParser.Absyn.Default.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof thriftParser.Absyn.DefInt) {
      thriftParser.Absyn.DefInt x = (thriftParser.Absyn.DefInt)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
