package thriftParser.Absyn; // Java Package generated by the BNF Converter.

public abstract class Enumeration implements java.io.Serializable {
  public abstract <R,A> R accept(Enumeration.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(thriftParser.Absyn.OneEnum p, A arg);

  }

}
