package thriftParser.Absyn; // Java Package generated by the BNF Converter.

public class Program extends Prog {
  public final ListClass listclass_;

  public Program(ListClass p1) { listclass_ = p1; }

  public <R,A> R accept(thriftParser.Absyn.Prog.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof thriftParser.Absyn.Program) {
      thriftParser.Absyn.Program x = (thriftParser.Absyn.Program)o;
      return this.listclass_.equals(x.listclass_);
    }
    return false;
  }

  public int hashCode() {
    return this.listclass_.hashCode();
  }


}
