package thriftParser.Absyn; // Java Package generated by the BNF Converter.

public abstract class Requirement implements java.io.Serializable {
  public abstract <R,A> R accept(Requirement.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(thriftParser.Absyn.REmp p, A arg);
    public R visit(thriftParser.Absyn.RReq p, A arg);
    public R visit(thriftParser.Absyn.ROpt p, A arg);

  }

}
