package thriftParser.Absyn; // Java Package generated by the BNF Converter.

public class TSet extends Type {
  public final Type type_;

  public TSet(Type p1) { type_ = p1; }

  public <R,A> R accept(thriftParser.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof thriftParser.Absyn.TSet) {
      thriftParser.Absyn.TSet x = (thriftParser.Absyn.TSet)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }


}
