package thriftParser.Absyn; // Java Package generated by the BNF Converter.

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(thriftParser.Absyn.TStr p, A arg);
    public R visit(thriftParser.Absyn.TInt p, A arg);
    public R visit(thriftParser.Absyn.TShort p, A arg);
    public R visit(thriftParser.Absyn.TLong p, A arg);
    public R visit(thriftParser.Absyn.TIdent p, A arg);
    public R visit(thriftParser.Absyn.TMap p, A arg);
    public R visit(thriftParser.Absyn.TList p, A arg);
    public R visit(thriftParser.Absyn.TSet p, A arg);

  }

}
